job/urls.py
from django.urls import path
from . import views

app_name = 'job'

urlpatterns = [
    path('ekle/', views.ekle, name='ekle'),
    path('<int:id>/',views.profil,name='profil')
]

panel/urls.py
from django.urls import path
from . import views

app_name = 'panel'

urlpatterns = [
    path('', views.panel, name='login'),
    # path('logout/',views.logoutUser,name='logout')
]

job/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User

# Create your models here.

class Job(models.Model):
    name = models.CharField(
        max_length=80,
        verbose_name='Yolcu Adı (Passenger Name)',
        null=False,
        blank=False
    )
    surname = models.CharField(
        max_length=80,
        verbose_name='Yolcu Soyadı (Passenger Surname)',
        null=False,
        blank=False
    )
    phone = models.CharField(
        verbose_name='Yolcu Telefon Numarası (Passenger Phone Number)',
        max_length=13,
        # validators=[MinLengthValidator(13,'Lütfen telefon numarasını alan kodu ile birlikte giriniz.')],
        default='',
        null=True,
        blank=True
    )
    email = models.EmailField(
        verbose_name='Yolcu Email Adresi (Passenger Email Address)',
        max_length=254,
        blank=True,
        null=True
    )
    location = models.CharField(
        max_length=120,
        verbose_name='Nereden (From)',
        null=False,
        blank=False
    )
    destination = models.CharField(
        max_length=120,
        verbose_name='Nereye (To)',
        null=False,
        blank=False
    )
    date = models.DateField(
        verbose_name='Tarih (Date)',
        null=False,
        blank=False
    )
    time = models.TimeField(
        verbose_name='Saat (Time)',
        null=False,
        blank=False
    )
    passenger_count = models.IntegerField(
        verbose_name='Yolcu Sayısı (Passenger Count)',
        choices=[(i , str(i)) for i in range(1,16)], 
        default=1
    )
    flight_code = models.CharField(
        verbose_name='Uçuş Kodu (Flight Code)',
        max_length=25,
        null=False,
        blank=False
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        verbose_name='Oluşturan Kullanıcı',
        related_name='job_created_by'
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name='Ücret (Price)'
    )
    currency = models.CharField(
        max_length=3,
        # choices=[
        #     ('USD', 'US Dollar'),
        #     ('EUR', 'Euro'),
        #     ('TRY', 'Turkish Lira'),
        # ],
        # default='TRY'
    )
    completed = models.BooleanField(
        default=False
    )
    
    def __str__(self):
        return f'{self.created_by.userprofile.otel.name}'
    
class Passenger(models.Model):
    job = models.ForeignKey(
        Job,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        verbose_name='Yolculuk',
        related_name='passenger_job'
    )
    name = models.CharField(
        max_length=80,
        verbose_name='Yolcu Adı (Passenger Name)',
        null=False,
        blank=False
    )
    surname = models.CharField(
        max_length=80,
        verbose_name='Yolcu Soyadı (Passenger Surname)',
        null=False,
        blank=False
    )
    # phone = models.CharField(
    #     verbose_name='Yolcu Telefon Numarası (Passenger Phone Number)',
    #     max_length=13,
    #     # validators=[MinLengthValidator(13,'Lütfen telefon numarasını alan kodu ile birlikte giriniz.')],
    #     default='',
    #     null=True,
    #     blank=True
    # )
    # email = models.EmailField(
    #     verbose_name='Yolcu Email Adresi (Passenger Email Address)',
    #     max_length=254,
    #     blank=True,
    #     null=True
    # )
    def __str__(self):
        return f'{self.name} {self.surname} - {self.job}'

otel/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User

# Create your models here.

class Otel(models.Model):
    name = models.CharField(
        max_length=80,
        null=False,
        blank=False,
        verbose_name='Otel Adı'
    )
    phone = models.CharField(
        max_length=13,
        validators=[MinLengthValidator(13,'Lütfen telefon numarasını alan kodu ile birlikte giriniz.')],
        default='+90',
        null=False,
        blank=False,
        verbose_name='Telefon Numarası'
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        verbose_name='Oluşturan Kullanıcı',
        related_name='otel_created_by'
    )
    def __str__(self):
        return self.name
    
class Pricing(models.Model):
    otel = models.ForeignKey(
        Otel,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        verbose_name='Otel',
        related_name='pricing_otel'
    )
    min_people = models.PositiveSmallIntegerField()
    max_people = models.PositiveSmallIntegerField(
        null=True,
        blank=True
    )
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name='Ücret (Price)'
    )
    currency = models.CharField(
        max_length=3,
        choices=[
            ('USD', 'USD'),
            ('EUR', 'EUR'),
            ('TRY', 'TRY'),
        ],
        default='TRY'
    )
    def __str__(self):
        if self.max_people:
            return f'{self.otel} - {self.min_people}-{self.max_people} -> {self.currency} {self.price}'
        return f'{self.otel} - {self.min_people}+ -> {self.currency} {self.price}'

panel/models.py
from django.db import models

# Create your models here.

panel/views.py
from django.shortcuts import render,redirect
from django.contrib import messages

from vehicle.models import Vehicle
from otel.models import Otel

# Create your views here.

def panel(request):
    if not request.user.is_authenticated:
        messages.warning(request,'Giriş yapmadan bu sayfayı göremezsiniz.')
        return redirect('/user/login')
    
    if request.user.userprofile.is_admin == False:
        messages.warning(request,'Yetkisiz giriş.')
        return redirect('/')
    
    vehicles = Vehicle.objects.filter(
        owner = request.user
    )
    otels = Otel.objects.filter(
        created_by = request.user
    )
    
    context = {
        'vehicles':vehicles,
        'otels':otels
    }
    return render(request,'panel.html',context)

templates/change_password.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">

  <h2>Şifre Değiştir</h2>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Şifreyi Güncelle</button>
  </form>
      </div>
</div>

{% endblock body %}

templates/ekle_arac.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class='row'>
    <div class='col-md-6 offset-md-3'>
        <h3>Otel Ekle</h3>
        <br>
        <form method='post'>
            {% csrf_token %}
            {{form | crispy}}
            <br>
            <button type='submit' class='btn btn-primary'>Ekle</button>
        </form>
    </div>

</div>

{% endblock body %}

templates/ekle_job.html
{% extends "layout.html" %} {% block body %} {% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Görev Ekle</h3>
    <br />
    <form method="post">
      {% csrf_token %} 
      {% comment %} {{form | crispy}} {% endcomment %} 
      {% comment %} <br /> {% endcomment %}
      <div class='row'>
        <div id="div_id_location" class="form-group col-lg-6">
          <label for="id_location" class="requiredField">
            Nereden (From)<span class="asteriskField">*</span>
          </label>
          <div>
            <input
              type="text"
              name="location"
              maxlength="120"
              class="textinput form-control"
              required
              id="id_location"
            />
          </div>
        </div>
        <div id="div_id_destination" class="form-group col-lg-6">
          <label for="id_destination" class="requiredField">
            Nereye (To)<span class="asteriskField">*</span>
          </label>
          <div>
            <input
              type="text"
              name="destination"
              maxlength="120"
              class="textinput form-control"
              required
              id="id_destination"
            />
          </div>
        </div>
      </div>

      <div id='name_surname'>
        <div class='row'>
          <div id="div_id_name" class="form-group col-lg-6">
            <label for="id_name" class="requiredField">
              Yolcu Adı (Passenger Name)<span class="asteriskField">*</span>
            </label>
            <div>
              <input
                type="text"
                name="name"
                maxlength="80"
                class="textinput form-control"
                required
                id="id_name"
              />
            </div>
          </div>
          <div id="div_id_surname" class="form-group col-lg-6">
            <label for="id_surname" class="requiredField">
              Yolcu Soyadı (Passenger Surname)<span class="asteriskField">*</span>
            </label>
            <div>
              <input
                type="text"
                name="surname"
                maxlength="80"
                class="textinput form-control"
                required
                id="id_surname"
              />
            </div>
          </div>
        </div>
      </div>
      <div class='row'>
        <div id="div_id_passenger_count" class="form-group col-lg-6">
          <label for="id_passenger_count" class="requiredField">
            Yolcu Sayısı (Passenger Count)<span class="asteriskField">*</span>
          </label>
          <div>
            <select
              name="passenger_count"
              class="select form-control"
              id="id_passenger_count"
              onchange="addRows(); updatePrice();"
            >
              <option value="1" selected>1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
              <option value="6">6</option>
              <option value="7">7</option>
              <option value="8">8</option>
              <option value="9">9</option>
              <option value="10">10</option>
              <option value="11">11</option>
              <option value="12">12</option>
              <option value="13">13</option>
              <option value="14">14</option>
              <option value="15">15</option>
            </select>
          </div>
        </div>

        <div class='form-group col-lg-6'>
          <label class="requiredField" style='color:red;'>
            Fiyat (Price)
          </label>
          <div>
            <input
              type="text"
              name="price"
              maxlength="13"
              class="textinput form-control"
              id="id_price"
              disabled
              value='0,00 {{price.currency}}'
            />
            <input
              type="hidden"
              name='hidden_price'
              id='id_hidden_price'
            />
            <input 
              type="hidden"
              name='hidden_currency'
              id='id_hidden_currency'
            />
          </div>
        </div>

      </div>

      <div class='row'>
        <div id="div_id_phone" class="form-group col-lg-6">
          <label for="id_phone" class="">
            Yolcu Telefon Numarası (Passenger Phone Number)
          </label>
          <div>
            <input
              type="text"
              name="phone"
              maxlength="13"
              class="textinput form-control"
              id="id_phone"
            />
          </div>
        </div>
        <div id="div_id_email" class="form-group col-lg-6">
          <label for="id_email" class="">
            Yolcu Email Adresi (Passenger Email Address)
          </label>
          <div>
            <input
              type="email"
              name="email"
              maxlength="254"
              class="emailinput form-control"
              id="id_email"
            />
          </div>
        </div>
      </div>

      <div class='row'>
        <div id="div_id_date" class="form-group col-lg-6">
          <label for="id_date" class="requiredField">
            Tarih (Date)<span class="asteriskField">*</span>
          </label>
          <div>
            <input
              type="date"
              name="date"
              class="dateinput form-control"
              required
              id="id_date"
            />
          </div>
        </div>
        <div id="div_id_time" class="form-group col-lg-6">
          <label for="id_time" class="requiredField">
            Saat (Time)<span class="asteriskField">*</span>
          </label>
          <div>
            <input
              type="time"
              name="time"
              class="timeinput form-control"
              required
              id="id_time"
            />
          </div>
        </div>
      </div>
      <div id="div_id_flight_code" class="form-group">
        <label for="id_flight_code" class="requiredField">
          Uçuş Kodu (Flight Code)<span class="asteriskField">*</span>
        </label>
        <div>
          <input
            type="text"
            name="flight_code"
            maxlength="25"
            class="textinput form-control"
            required
            id="id_flight_code"
          />
        </div>
      </div>

      <br />
      <button type="submit" class="btn btn-primary">Ekle</button>
    </form>
  </div>
</div>

<script>
// let rowCounter = 1; // Başlangıç için bir sayaç oluşturuyoruz

function addRows() {
    const numRows = parseInt(document.getElementById('id_passenger_count').value); // Seçilen değeri al ve sayıya dönüştür
    const container = document.getElementById('name_surname'); // Satırların ekleneceği container
    const existingRows = container.querySelectorAll('.row'); // Mevcut satırları al
    const currentRowCount = existingRows.length; // Şu anki satır sayısını al

    // Eksik olan satır sayısı
    const rowsToAdd = numRows - currentRowCount;

    // Eğer eksik satır varsa, ekle
    for (let i = 0; i < rowsToAdd; i++) {
        const initialRow = container.querySelector('.row'); // İlk satırı referans al
        const newRow = initialRow.cloneNode(true); // İlk row'u çoğalt
        
        // Yeni row'daki input alanlarını temizle
        newRow.querySelectorAll('input').forEach(input => {
            input.value = ''; // Her inputun değerini temizle
        });

        // Yeni satırdaki 'name' attribute'unu değiştirme
        newRow.querySelectorAll('[name]').forEach(element => {
            // Örneğin "name" -> "name_1" şeklinde name attribute'unu oluşturuyoruz
            const newName = `${element.name}_passenger`;
            element.name = newName; // Yeni name'i ata
        });

        // Yeni row'u container'a ekle
        container.appendChild(newRow);
        
        // Sayaç artırılacak
        // rowCounter++;
    }

    // Fazla olan satırları sil
    if (rowsToAdd < 0) {
        for (let i = 0; i < Math.abs(rowsToAdd); i++) {
            const rowToRemove = existingRows[existingRows.length - 1 - i]; // Son satırları seç
            rowToRemove.remove(); // Sil
        }
    }

}

</script>

<script>
function updatePrice() {

    const numRows = parseInt(document.getElementById('id_passenger_count').value); // Seçilen değeri al ve sayıya dönüştür
    const price_input = document.getElementById('id_price');
    const hidden_price = document.getElementById('id_hidden_price');
    const hidden_currency = document.getElementById('id_hidden_currency');

    const prices = JSON.parse('{{ prices|escapejs }}');
    console.log(prices)

    prices.forEach((price) => {
      if (price.max_people === 0) {
        price.max_people = 999999999
      }
      if (parseInt(price.min_people) <= numRows && numRows <= parseInt(price.max_people)) {
        price_input.value = `${price.price} ${price.currency}`
        hidden_price.value = price.price
        hidden_currency.value = price.currency
      }
    })
}

document.addEventListener('DOMContentLoaded', function() {
  updatePrice();
});


</script>

{% endblock body %}

templates/ekle_otel.html
{% extends "layout.html" %} 

{% block body %} 

{% load crispy_forms_tags %}
{% load static %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Otel Ekle</h3>
    <br />
    <form method="post">
      {% csrf_token %} 
      <div class="row">
        <div id="div_id_name" class="form-group col-lg-6">
          <label for="id_name" class="requiredField">
            Otel Adı<span class="asteriskField">*</span>
          </label>
          <div>
            <input
              type="text"
              name="name"
              maxlength="80"
              class="textinput form-control"
              required
              id="id_name"
            />
          </div>
        </div>
        <div id="div_id_phone" class="form-group col-lg-6">
          <label for="id_phone" class="requiredField">
            Telefon Numarası<span class="asteriskField">*</span>
          </label>
          <div>
            <input
              type="text"
              name="phone"
              value="+90"
              maxlength="13"
              class="textinput form-control"
              required
              id="id_phone"
            />
          </div>
        </div>
      </div>

      <div id='pricing_row' class="row">
        <div id="div_id_min_people" class="form-group col-lg-2">
          <label for="id_min_people" class="requiredField">
            Min people<span class="asteriskField">*</span>
          </label>
          <div>
            <input
              type="number"
              name="min_people"
              min="0"
              class="numberinput form-control"
              required
              id="id_min_people"
              value=1
              readonly
              onchange='handleMinChange(this)'
            />
          </div>
        </div>
        <div id="div_id_max_people" class="form-group col-lg-2">
          <label for="id_max_people" class="">
            Max people<span id='max_span' class="asteriskField">*</span>
          </label>
          <div>
            <input
              type="number"
              name="max_people"
              min="0"
              class="numberinput form-control"
              id="id_max_people"
              required
              onchange='handleMaxChange(this)'
            />
          </div>
        </div>

        <div id="div_id_price" class="form-group col-lg-2">
          <label for="id_price" class="requiredField">
            Ücret (Price)<span class="asteriskField">*</span>
          </label>
          <div>
            <input
              type="number"
              name="price"
              step="0.01"
              class="numberinput form-control"
              required
              id="id_price"
            />
          </div>
        </div>
        <div id="div_id_currency" class="form-group col-lg-2">
          <label for="id_currency" class="requiredField">
            Currency<span class="asteriskField">*</span>
          </label>
          <div>
            <select
              name="currency"
              class="select form-control"
              id="id_currency"
            >
              <option value="EUR" selected>EUR</option>
              <option value="USD">USD</option>
              <option value="TRY">TRY</option>
            </select>
          </div>
        </div>

        <div class='form-group col-lg-2'>
          <label for='pricing_ekle' class='requiredField'>
            Ekle
          </label>
          <div>
            <button id='pricing_ekle' class='btn btn-success' onclick="addPricingRow(event)">Yeni Ekle</button>
          </div>
        </div>

        <div id='div_sil_button' class='form-group col-lg-2' style='display:none;'>
          <label for='pricing_sil' class='requiredField'>
            Sil
          </label>
          <div>
            <button id='pricing_sil' class='btn btn-danger' onclick="removePricingRow(event)">Sil</button>
          </div>
        </div>
      </div>

      <hr />

      <div id="div_id_username" class="form-group">
        <label for="id_username" class="requiredField">
          Kullanıcı adı<span class="asteriskField">*</span>
        </label>
        <div>
          <input
            type="text"
            name="username"
            maxlength="150"
            autofocus
            class="textinput form-control"
            required
            aria-describedby="id_username_helptext"
            id="id_username"
          />
          <small id="hint_id_username" class="form-text text-muted"
            >Zorunlu. 150 karakter ya da daha az olmalı. Sadece harfler,
            rakamlar ve @/./+/-/_ karakterleri kullanılabilir.</small
          >
        </div>
      </div>

      <div class="row">
        <div id="div_id_password1" class="form-group col-lg-6">
          <label for="id_password1" class="">
            Parola<span class="asteriskField">*</span>
          </label>
          <div>
            <input
              type="password"
              name="password1"
              autocomplete="new-password"
              class="passwordinput form-control"
              aria-describedby="id_password1_helptext"
              id="id_password1"
            />
            <small id="hint_id_password1" class="form-text text-muted"
              ><ul>
                <li>
                  Parolanız diğer kişisel bilgileriniz ile çok benzer olamaz.
                </li>
                <li>Parolanız en az 8 karakter içermek zorundadır.</li>
                <li>Parolanız yaygın olarak kullanılan bir parola olamaz.</li>
                <li>Parolanız tamamıyla sayısal olamaz.</li>
              </ul></small
            >
          </div>
        </div>
        <div id="div_id_password2" class="form-group col-lg-6">
          <label for="id_password2" class="">
            Parola onayı<span class="asteriskField">*</span>
          </label>
          <div>
            <input
              type="password"
              name="password2"
              autocomplete="new-password"
              class="passwordinput form-control"
              aria-describedby="id_password2_helptext"
              id="id_password2"
            />
            <small id="hint_id_password2" class="form-text text-muted"
              >Doğrulama için önceki gibi aynı parolayı girin.</small
            >
          </div>
        </div>
      </div>

      <br />
      <button type="submit" class="btn btn-primary">Ekle</button>
    </form>
  </div>
</div>

<script src='{% static "js/ekle_otel.js" %}'></script>

{% endblock body %}

templates/kullanici_ekle.html
{% extends 'layout.html' %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kullanıcı Ekle</h3>
        <br>
        <form method="post">
            {% csrf_token %}
            {{form | crispy}}
            <br>    
            <button type='submit' class='btn btn-primary'>Giris Yap</button>
        </form>
    
    </div>
</div>

{% endblock body %}

templates/login.html
{% extends 'layout.html' %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giris Yap</h3>
        <br>
        <form method="post">
            {% csrf_token %}
            {{form | crispy}}
            <br>    
            <button type='submit' class='btn btn-primary'>Giris Yap</button>
        </form>
    
    </div>
</div>

{% endblock body %}

templates/otel_guncelle.html
{% extends "layout.html" %} 

{% block body %} 

{% load crispy_forms_tags %}
{% load static %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Otel Güncelle</h3>
    <br />
    <form method="post">
      {% csrf_token %} {% comment %} {{otelform | crispy}}
      <br />
      {{userform | crispy}} {% endcomment %}
      <div class="row">
        <div id="div_id_name" class="form-group col-lg-6">
          <label for="id_name" class="requiredField">
            Otel Adı<span class="asteriskField">*</span>
          </label>
          <div>
            <input
              type="text"
              name="name"
              maxlength="80"
              class="textinput form-control"
              required
              id="id_name"
              value='{{otel.name}}'
            />
          </div>
        </div>
        <div id="div_id_phone" class="form-group col-lg-6">
          <label for="id_phone" class="requiredField">
            Telefon Numarası<span class="asteriskField">*</span>
          </label>
          <div>
            <input
              type="text"
              name="phone"
              value="{{otel.phone}}"
              maxlength="13"
              class="textinput form-control"
              required
              id="id_phone"
            />
          </div>
        </div>
      </div>

        {% for price in prices %}
        
      <div id='pricing_row' class="row">
        <div id="div_id_min_people" class="form-group col-lg-2">
          <label for="id_min_people" class="requiredField">
            Min people<span class="asteriskField">*</span>
          </label>
          <div>
            <input
              type="number"
              name="min_people"
              min="0"
              class="numberinput form-control"
              required
              id="id_min_people"
              value='{{price.min_people}}'
              onchange='handleMinChange(this)'
              {% if price.min_people == 1 %}
                readonly
              {% endif %}
            />
            <input type="hidden" name="price_id" id="id_price_id" value='{{price.id}}'>
          </div>
        </div>
        <div id="div_id_max_people" class="form-group col-lg-2">
          <label for="id_max_people" class="">
            Max people 
            {% if price.max_people != 0 %}
                <span id='max_span' class="asteriskField">*</span>
            {% endif %}
          </label>
          <div>
            <input
              type="number"
              name="max_people"
              min="0"
              class="numberinput form-control"
              id="id_max_people"
              onchange='handleMaxChange(this)'
              {% if price.max_people != 0 %}
                  value='{{price.max_people}}'
                  required
              {% endif %}
            />
          </div>
        </div>

        <div id="div_id_price" class="form-group col-lg-2">
          <label for="id_price" class="requiredField">
            Ücret (Price)<span class="asteriskField">*</span>
          </label>
          <div>
            <input
              type="text"
              name="price"
              step="0.01"
              class="numberinput form-control"
              required
              id="id_price"
              value='{{price.price}}'
            />
          </div>
        </div>
        <div id="div_id_currency" class="form-group col-lg-2">
          <label for="id_currency" class="requiredField">
            Currency<span class="asteriskField">*</span>
          </label>
          <div>
            <select
              name="currency"
              class="select form-control"
              id="id_currency"
            >
              <option 
                value="EUR" 
                {% if price.currency == 'EUR' %}
                    selected
                {% endif %}
                >EUR</option>
              <option 
                value="USD" 
                {% if price.currency == 'USD' %}
                    selected
                {% endif %}
                >USD</option>
              <option 
                  value="TRY" 
                {% if price.currency == 'TRY' %}
                    selected
                {% endif %}
                >TRY</option>
            </select>
          </div>
        </div>
      </div>
        {% endfor %}

      <div id='pricing_row' class="row">
        <div id="div_id_min_people" class="form-group col-lg-2">
          <label for="id_min_people" class="requiredField">
            Min people<span class="asteriskField" style='display:none;'>*</span>
          </label>
          <div>
            <input
              type="number"
              name="min_people"
              min="0"
              class="numberinput form-control"
              id="id_min_people"
              onchange='handleMinChange(this); handleRowChange(this);'
            />
          </div>
        </div>
        <div id="div_id_max_people" class="form-group col-lg-2">
          <label for="id_max_people" class="">
            Max people<span id='max_span' class="asteriskField" style='display:none;'>*</span>
          </label>
          <div>
            <input
              type="number"
              name="max_people"
              min="0"
              class="numberinput form-control"
              id="id_max_people"
              onchange='handleMaxChange(this); handleRowChange(this);'
            />
          </div>
        </div>

        <div id="div_id_price" class="form-group col-lg-2">
          <label for="id_price" class="requiredField">
            Ücret (Price)<span class="asteriskField" style='display:none;'>*</span>
          </label>
          <div>
            <input
              type="number"
              name="price"
              step="0.01"
              class="numberinput form-control"
              id="id_price"
              onchange='handleRowChange(this)'
            />
          </div>
        </div>
        <div id="div_id_currency" class="form-group col-lg-2">
          <label for="id_currency" class="requiredField">
            Currency<span class="asteriskField" style='display:none;'>*</span>
          </label>
          <div>
            <select
              name="currency"
              class="select form-control"
              id="id_currency"
              onchange='handleRowChange(this)'
            >
              <option value="" selected>----------</option>
              <option value="EUR">EUR</option>
              <option value="USD">USD</option>
              <option value="TRY">TRY</option>
            </select>
          </div>
        </div>

        <div class='form-group col-lg-2'>
          <label for='pricing_ekle' class='requiredField'>
            Ekle
          </label>
          <div>
            <button id='pricing_ekle' class='btn btn-success' onclick="addPricingRow(event)">Yeni Ekle</button>
          </div>
        </div>

        <div id='div_sil_button' class='form-group col-lg-2' style='display:none;'>
          <label for='pricing_sil' class='requiredField'>
            Sil
          </label>
          <div>
            <button id='pricing_sil' class='btn btn-danger' onclick="removePricingRow(event)">Sil</button>
          </div>
        </div>
      </div>



      <hr />
      <button type="submit" class="btn btn-primary">Güncelle</button>
    </form>
  </div>
</div>

<script src='{% static "js/guncelle_otel.js" %}'></script>

{% endblock body %}